### ISSUE TITLE
Can't move up in *.tutor files

### ISSUE THREAD

**Issue by Pyrohh** [fmoralesc/vim-tutor-mode#1]
I use the following mappings in my vimrc:
```vim
noremap j h
noremap k j
noremap l k
noremap ; l
```
`:verbose map key` for `h` and `l` shows the following:
```vim
   l           *@tutor#ForwardSkipConceal(v:count1)
        Last set from ~/.nvim/plugged/vim-tutor-mode/ftplugin/tutor.vim
   l           * k
        Last set from ~/.nvim/nvimrc


   h           *@tutor#BackwardSkipConceal(v:count1)
        Last set from ~/.nvim/plugged/vim-tutor-mode/ftplugin/tutor.vim
```

**Comment by fmoralesc** [comment]
Ah! I have that to skip over the concealed sections on normal mode. I'm writing a check to redirect the mappings in your scenario, gimme a sec.

**Comment by Pyrohh** [comment]
I saw the commit message, but that fixes it for now.

**Comment by fmoralesc** [comment]
Commit 2e020a61e019bbd86bb498b5a9651de082f5fd15 should fix it entirely. Please confirm.

**Comment by Pyrohh** [comment]
That works fine. At first glance, would there be any downside to wrapping the other mappings in that?

**Comment by fmoralesc** [comment]
I think it's best to keep those left in `ftplugin/tutor.vim` alone, because if they change, we would no longer have a common set of mappings for the links. Navigation is different. 

That said, I'm not sure how it would work with the mappings in `autoload/tutor.vim:tutor#SetSampleTextMappings()`.

**Comment by Pyrohh** [comment]
I think I understand, anyways thanks for the fix. Feel free to close this.
