### ISSUE TITLE
`:Tutor nonexistent-tutorial` incorrect message

### ISSUE THREAD

**Issue by Pyrohh** [fmoralesc/vim-tutor-mode#14]
`:Tutor non-existant-tutorial` results in:
```vim
Several tutorials with that name found. Select one:
Type number and <Enter> or click with mouse (empty cancels):
```
but there were no tutorials, and there is no numbered list.

**Comment by fmoralesc** [comment]
This was an oversight. I didn't code any behavior for when no tutorials are found, so it fell back on the path for multiple candidates. Should be fixed now.

**Comment by Pyrohh** [comment]
I don't know much about vimscript, but here's my error message:

```vim
Error detected while processing function tutor#TutorCmd:
line    8:
No tutorials with that name found.
```

Would it be possible to catch that first error so only the second shows?

**Comment by fmoralesc** [comment]
We can "fake" the error message, or just use `echom` instead.
