### ISSUE TITLE
Ignore file extension if given

### ISSUE THREAD

**Issue by Pyrohh** [fmoralesc/vim-tutor-mode#16]
`:Tutor example.tutor` throws an error despite `example.tutor` existing, while `:Tutor example` works.

Perhaps if the argument ends in `.tutor`, then open that instead.

**Comment by fmoralesc** [comment]
:+1:

**Comment by fmoralesc** [comment]
Fixed. Should we allow passing arbitrary paths too? (I think not, but wanted to know what you think).

**Comment by Pyrohh** [comment]
> Should we allow passing arbitrary paths too

I don't think so. If users want to open a tutor file then they can just use `:e` and let the ftdetect/plugin take effect.
