### ISSUE TITLE
Syntax improvement ideas

### ISSUE THREAD

**Issue by Pyrohh** [fmoralesc/vim-tutor-mode#21]
- [ ] Stop using Unicode so much, it doesn't necessarily display properly.
  - [x] `« »`, e.g. `[«<ESCAPE>»](<Esc>)`
  - [ ] Maybe use just colors to indicate success instead of a checkmark or "X"
- [x] Perhaps try to emulate markdown more
- [ ] Significant whitespace maybe? 
- [x] Improve code block annotations, e.g. `viml`, `normal`, could be `cmd` or `ex` and `norm`, to indicate the mode.

Please post any ideas you have below.

**Comment by Pyrohh** [comment]
Damn @fmoralesc hacking my computer and editing my posts!

**Comment by fmoralesc** [comment]
![yup](http://smhttp.23575.nexcesscdn.net/80ABE1/sbmedia/blog/wp-content/uploads/2013/04/computer-hacker.jpg)

**Comment by Pyrohh** [comment]
Since any reasonable person would conclude we have reached the apex of syntax elegance, with a cool factor of 10**500, imma close this.
