### ISSUE TITLE
":Tutor vimtutor" fails with error

### ISSUE THREAD

**Issue by miquelbeltran** [fmoralesc/vim-tutor-mode#3]
I could not copy from my terminal so I made a screenshot.

System: Mac OS X 10.10, Vim 7.3, [my .vimrc](https://github.com/miquelbeltran/dotfiles/blob/master/.vimrc)

- Plugin installed using Vundle.
- Start vim
- run :Tutor vimtutor
- Error appears on the screen, Tutor does not start.

Let me know if you need more info. (I'm also very new to vim)

![captura de pantalla 2015-01-04 17 34 34](https://cloud.githubusercontent.com/assets/2494376/5606642/7178ccfa-9438-11e4-837e-40b821790ff9.png)

**Comment by fmoralesc** [comment]
Thanks for the report.

It seems like in vim 7.3 `globpath()` took 3 arguments instead of 4. I just pushed a fix to this, please confirm.

**Comment by miquelbeltran** [comment]
Yes, it works now.

Thanks!
