### ISSUE TITLE
Plugin doesn't work well on terminal with 80 column width

### ISSUE THREAD

**Issue by pickfire** [fmoralesc/vim-tutor-mode#30]
Hi, I just found out that neovim looks somewhat ugly when being used with a 80 characters width terminal and it needs 83 character to look nice instead.

This is what neovim looks like during startup

![2016-07-08-122521_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/16677344/43d37ed6-4507-11e6-9249-65cc4728d6d2.png)

Compared to vim which is gracefully centered

![2016-07-08-122627_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/16677346/43d9c278-4507-11e6-8ea3-286b01dc12ef.png)

The new `Tutor` for neovim which have good feature

![2016-07-08-122550_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/16677345/43d777b6-4507-11e6-90d1-55410e714c22.png)

But the old help page definitely looks a lot neater

![2016-07-08-122616_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/16677343/43d2e3a4-4507-11e6-8e34-be19f8cb26e4.png)

I just put more information about neovim here since you are one of the neovim developers IIRC, maybe I can also open an issue there.

I think those `| ` folds aren't necessary for beginners so disabling them would be good.

**Comment by fmoralesc** [comment]
I'm working on this, there's still some work to do (need to reflow the tutorials so they work better at 80 columns width). It is somewhat complicated due to the way we use conceals.

**Comment by pickfire** [comment]
Ah, thanks a lot!
