### ISSUE TITLE
Function Already in Use

### ISSUE THREAD

**Issue by cxgslegend** [fmoralesc/vim-tutor-mode#34]
When I try to load Tutor in neovim, it tells me it cannot redefine the tutor#TutorCmd because it is in use. 

I assume this is because there is already a similar tutor file that ships with neovim. I am not sure why it's already running 

<img width="881" alt="Screen Shot 2020-06-27 at 1 07 37 AM" src="https://user-images.githubusercontent.com/8932713/85915177-4fbe9180-b813-11ea-8bac-933825719f40.png">

**Comment by fmoralesc** [comment]
Yes, neovim already ships vim-tutor-mode, so it is not necessary to install this over it (actually, it might be better to use the nvim provided files anyway, because they are slightly more recent than those in this repo).

**Comment by cxgslegend** [comment]
Thank you for responding. I didn't know the nvim tutor.vim provided the same functionality as this plugin. I assumed they were different and incompatible. 

The reason I found this plugin was because I use vim-pad. So when I tried running `Tutor: pad`, and it said "No tutorial with that name found". So I assumed it was just because the vim-pad author wrote the tutorial file with vim-tutor-mode plugin in mind, and not with whatever nvim was using. 

So if the nvim Tutor mode, and the vim-tutor-mode plugin are the same, why does `Tutor: pad` not work? Is it possible their are slight differences between them? 

I apologize if this obvious.

**Comment by fmoralesc** [comment]
It's alright.  I had forgotten vim-pad provided a tutorial file! The path that the file is in is wrong for recent versions of the Tutor command: instead of looking for files in `tutorials/`, it looks for files in `tutor/`. Note that the format that the file is in might also be outdated by now...

**Comment by cxgslegend** [comment]
Oh, I see. I will submit an issue with the vim-pad author then. 

Thank you for your help. It was very kind of you (and thanks for the awesome plugin).

**Comment by fmoralesc** [comment]
I am the author of vim-pad :p I will commit the fix in a few minutes ;)

**Comment by fmoralesc** [comment]
>  I didn't know the nvim tutor.vim provided the same functionality as this plugin. I assumed they were different and incompatible.

This was a testbed for the nvim plugin, so we could try the idea out before merging it into the nvim codebase. Once it was merged, most changes actually happened in the nvim repo.

**Comment by cxgslegend** [comment]
> I am the author of vim-pad :p I will commit the fix in a few minutes ;)

Oh, I apologize for not noticing that. Thank you again. You can close this issue if you want. I promise I won't bother you anymore 😄 

> This was a testbed for the nvim plugin, so we could try the idea out before merging it into the nvim codebase. Once it was merged, most changes actually happened in the nvim repo.

That's awesome! Thank you for all the amazing work you have contributed to the vim/nvim ecosystem.

**Comment by fmoralesc** [comment]
Thanks for the kind words.
