### ISSUE TITLE
Turn off vim-indent-guides when in tutor

### ISSUE THREAD

**Issue by simonweil** [fmoralesc/vim-tutor-mode#9]
Hi and thank you for a great learning method!

I'm using the plugin [vim-indent-guides](https://github.com/nathanaelkane/vim-indent-guides), the issue is that when in the tutor buffer the indent guides are on.

Is there a way to make it go off in tutor buffers?
It would be great if you add this "exception" to your plugin.

**Comment by fmoralesc** [comment]
Will see what I can do.

**Comment by simonweil** [comment]
Thanks :)

**Comment by fmoralesc** [comment]
It seems like this can be fixed by having

  let g:indent_guides_exclude_filetypes = ['help', 'tutor']

in your vimrc. I'll try to make it so vim-tutor-mode adds it automatically if the variable exists.

**Comment by fmoralesc** [comment]
@simonweil I just pushed a fix for this. Please confirm.

**Comment by simonweil** [comment]
Perfect!!!
Thank you very much :)
